# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pool:
  name: Default 
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'roleasc'   # Service Connection adın
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Assigning Contributor role to user..."
      az role assignment create \
        --assignee 8662b771-5dc0-4b2c-8c60-2cf75dd12ae9 \
        --role "Contributor" \
        --scope /subscriptions/fe261f48-3d9f-414f-b081-a4ccd33202f4