parameters:
- name: subscriptionId
  displayName: Azure Subscription ID
  type: string
  default: 'fe261f48-3d9f-414f-b081-a4ccd33202f4'  # Varsayılan abonelik ID'niz

- name: resourceGroupName
  displayName: Resource Group Name
  type: string
  default: 'TestResourceGroup'

- name: location
  displayName: Azure Region
  type: string
  default: 'westeurope'
  values:
  - 'eastus'
  - 'westeurope'
  - 'northeurope'
  - 'southeastasia'

trigger: none  # Manuel çalıştırma için

pool:
  name: Default

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'ed-sc'  # Service connection adı
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Parametrelerden gelen değerleri kullanma
      az account set --subscription ${{ parameters.subscriptionId }}
      
      Write-Host "Creating Resource Group: ${{ parameters.resourceGroupName }} in ${{ parameters.location }}"
      
      az group create `
        --name ${{ parameters.resourceGroupName }} `
        --location ${{ parameters.location }}
      
      # Oluşturulan RG bilgilerini görüntüleme
      az group show --name ${{ parameters.resourceGroupName }}